### ISSUE TITLE
ValueException should be ValueError

### ISSUE THREAD

**Issue by jgosmann** [tcstewar/pytry#15]
When trying to redefine a parameter:
```
Traceback (most recent call last):
  File "/home/jgosmann/.pyenv/versions/3.5.3/bin/pytry", line 11, in <module>
    sys.exit(run())
  File "/home/jgosmann/.pyenv/versions/3.5.3/lib/python3.5/site-packages/pytry/cmdline.py", line 35, in run
    t = trials[0]()
  File "/home/jgosmann/.pyenv/versions/3.5.3/lib/python3.5/site-packages/pytry/trial.py", line 21, in __init__
    self.params()
  File "imem/models/neural_tcm.py", line 38, in params
    self.param("save debug data", debug=False)
  File "/home/jgosmann/.pyenv/versions/3.5.3/lib/python3.5/site-packages/pytry/trial.py", line 36, in param
    raise ValueException('Cannot redefine parameter "%s"' % k)
NameError: name 'ValueException' is not defined
```

**Comment by tcstewar** [comment]
That's been fixed since https://github.com/tcstewar/pytry/commit/2d57adef9564817daedb7ad1602cd940c6cdf9cf

I haven't done a release since then though....
