### ISSUE TITLE
Fails to discover NengoTrial

### ISSUE THREAD

**Issue by jgosmann** [tcstewar/pytry#2]
Using the `pytry` command I get this error:
```
Traceback (most recent call last):
  File "/home/jgosmann/.virtualenvs/kajic-frontiers2016/bin/pytry", line 7, in <module>
    from pytry.cmdline import run
  File "/home/jgosmann/.virtualenvs/kajic-frontiers2016/lib/python3.5/site-packages/pytry/cmdline.py", line 30
    print 'Error: no pytry.Trial class found in %s' % filename
                                                  ^
SyntaxError: Missing parentheses in call to 'print'
```
even though there is a trial class defined:
```python
class SpaRat(pytry.NengoTrial):
    # ...
```

**Comment by jgosmann** [comment]
This is actually just the syntax error in reported in #1.
