### ISSUE TITLE
Exception when redefining parameter is not defined

### ISSUE THREAD

**Issue by jgosmann** [tcstewar/pytry#8]
```
Traceback (most recent call last):
  File "/home/jgosmann/.pyenv/versions/3.5.2/bin/pytry", line 11, in <module>
    sys.exit(run())
  File "/home/jgosmann/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pytry/cmdline.py", line 35, in run
    t = trials[0]()
  File "/home/jgosmann/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pytry/trial.py", line 21, in __init__
    self.params()
  File "cogsci17_decide/trial.py", line 13, in params
    self.param("seed", seed=1)
  File "/home/jgosmann/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pytry/trial.py", line 36, in param
    raise ValueException('Cannot redefine parameter "%s"' % k)
NameError: name 'ValueException' is not defined
```

**Comment by tcstewar** [comment]
Wow do I need to write more tests....  thank you!
