### ISSUE TITLE
GUI option does not work

### ISSUE THREAD

**Issue by jgosmann** [tcstewar/pytry#9]
```
Traceback (most recent call last):
  File "/home/jgosmann/.pyenv/versions/3.5.2/bin/pytry", line 11, in <module>
    sys.exit(run())
  File "/home/jgosmann/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pytry/cmdline.py", line 37, in run
    t.run(**args)
  File "/home/jgosmann/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pytry/trial.py", line 87, in run
    result = self.execute_trial(p)
  File "/home/jgosmann/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pytry/nengo.py", line 33, in execute_trial
    editor=False,
TypeError: __init__() got an unexpected keyword argument 'editor'
```

**Comment by tcstewar** [comment]
Ah...  this is dependent on the nengo version...  I'll add some handling for older versions.

**Comment by jgosmann** [comment]
I've got the latest versions installed:
```
nengo==2.3.0
nengo-gui==0.2.0
```

**Comment by tcstewar** [comment]
Sorry, I meant the ```nengo_gui``` version.  I'd been working with master, but that's drifted a bit since ```0.2.0```.

**Comment by jgosmann** [comment]
Freshly installing `nengo_gui` and `pytry` with `pip` seems to still produces this issue. :(

**Comment by jgosmann** [comment]
Also after updating `nengo_gui` to the current master version, it starts, but an empty editor also appears and I cannot run the model (because no model is defined), but the netgraph shows up.

**Comment by jgosmann** [comment]
Seems like I got it working with:
* nengo_gui from pip/PyPI
* pytry revision 2d43d25453 (master might work too, didn't test that)

**Comment by tcstewar** [comment]
Ah yes...  I should do another release so that that fix is in the pip-installed version.
